project/NRG_Backend/Areas/SA/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NRG_Core.Context;
using NRG_Core.DataModels;
using NRG_Core.Interface;
using NRG_Core.Repository;
using System;

namespace NRG_Backend.Areas.SA.Controllers
{
    [Area("SA")]
    [Authorize]
    public class DefaultController : Controller
    {
        private readonly ILogger _log;

        public DefaultController(WebContext db)
        {
            _log = new RLogger(db);
        }

        public JsonResult GetOrder()
        {
            var data = new Object();
            try
            {
                var tgl = DateTime.Now;
                var dt = string.Empty;

                if (!string.IsNullOrEmpty(dt))
                    data = JsonConvert.DeserializeObject(dt);
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Default.GetOrder.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }
            return Json(new { data });
        }

        public ActionResult Index()
        {
            ViewBag.Message = string.Empty;
            var msg = HttpContext.Session.GetString("TmpError");
            if (!string.IsNullOrEmpty(msg))
            {
                ViewBag.Message = msg;
                HttpContext.Session.SetString("TmpError", string.Empty);
            }
            return View();
        }
    }
}

project/NRG_Backend/Areas/SA/Controllers/MasterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NRG_Core.Context;
using NRG_Core.DataModels;
using NRG_Core.Interface;
using NRG_Core.Repository;
using System;
using System.Collections.Generic;

namespace NRG_Backend.Areas.SA.Controllers
{
    [Area("SA")]
    [Authorize]
    public class MasterController : Controller
    {
        private readonly ILogger _log;
        private readonly IHospital _hospital;
        private readonly ISurgeon _surgeon;
        private readonly IPatient _patient;

        public MasterController(WebContext db)
        {
            _log = new RLogger(db);
            _hospital = new RHospital(db);
            _surgeon = new RSurgeon(db);
            _patient = new RPatient(db);
        }

        #region Hospital
        public JsonResult GetHospital(int id)
        {
            var data = new Object();

            try
            {
                var result = JsonConvert.DeserializeObject<ResponseEnt>(_hospital.All(id));
                if (!string.IsNullOrEmpty(result.data))
                {
                    data = JsonConvert.DeserializeObject<List<MHospital>>(result.data);
                }
                else
                {
                    HttpContext.Session.SetString("TmpError", result.message);
                    _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.GetHospital-" + result.message, CreateBy = "system", CreateDate = DateTime.Now });
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.GetHospital.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }
            return Json(new { data });
        }

        public ActionResult Hospital()
        {
            var login = HttpContext.Session.GetString("uname");
            if (string.IsNullOrEmpty(login))
            {
                login = HttpContext.Session.GetString("nname");
                if (string.IsNullOrEmpty(login)) return Redirect("~/Home");
            }

            ViewBag.Message = string.Empty;
            var msg = HttpContext.Session.GetString("TmpError");
            if (!string.IsNullOrEmpty(msg))
            {
                ViewBag.Message = msg;
                HttpContext.Session.SetString("TmpError", string.Empty);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateHospital(MHospital prm)
        {
            try
            {
                var login = HttpContext.Session.GetString("uname");
                if (string.IsNullOrEmpty(login))
                {
                    login = HttpContext.Session.GetString("nname");
                    if (string.IsNullOrEmpty(login)) return Redirect("~/Home");
                }

                if (!string.IsNullOrEmpty(prm.Name))
                {
                    if (string.IsNullOrEmpty(prm.CreateBy)) prm.CreateBy = login;
                    var result = JsonConvert.DeserializeObject<ResponseEnt>(_hospital.Update(prm));
                    if (!result.status)
                    {
                        HttpContext.Session.SetString("TmpError", result.message);
                        _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.UpdateHospital-" + result.message, CreateBy = "system", CreateDate = DateTime.Now });
                    }
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.UpdateHospital.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }
            return RedirectToAction(nameof(Hospital));
        }

        public bool DeleteHospital(int id)
        {
            var rets = false;

            try
            {
                var username = HttpContext.Session.GetString("uname");
                if (string.IsNullOrEmpty(username))
                {
                    username = HttpContext.Session.GetString("nname");
                    if (string.IsNullOrEmpty(username)) return false;
                }

                if (id > 0)
                {
                    var result = JsonConvert.DeserializeObject<ResponseEnt>(_hospital.Remove(id, username));
                    if (result.status)
                    {
                        rets = true;
                    }
                    else
                    {
                        HttpContext.Session.SetString("TmpError", result.message);
                        _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.DeleteHospital-" + result.message, CreateBy = "system", CreateDate = DateTime.Now });
                    }
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.DeleteHospital.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }
            return rets;
        }
        #endregion

        #region Surgeon
        public JsonResult GetSurgeon(int id)
        {
            var data = new Object();

            try
            {
                var result = JsonConvert.DeserializeObject<ResponseEnt>(_surgeon.All(id));
                if (!string.IsNullOrEmpty(result.data))
                {
                    data = JsonConvert.DeserializeObject<List<MSurgeon>>(result.data);
                }
                else
                {
                    HttpContext.Session.SetString("TmpError", result.message);
                    _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.GetSurgeon-" + result.message, CreateBy = "system", CreateDate = DateTime.Now });
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.GetSurgeon.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }            
            return Json(new { data });
        }

        public ActionResult Surgeon()
        {
            var username = HttpContext.Session.GetString("uname");
            if (string.IsNullOrEmpty(username))
            {
                username = HttpContext.Session.GetString("nname");
                if (string.IsNullOrEmpty(username)) return Redirect("~/Home");
            }
            
            ViewBag.Message = string.Empty;
            var msg = HttpContext.Session.GetString("TmpError");
            if (!string.IsNullOrEmpty(msg))
            {
                ViewBag.Message = msg;
                HttpContext.Session.SetString("TmpError", string.Empty);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateSurgeon(MSurgeon prm)
        {
            try
            {
                var username = HttpContext.Session.GetString("uname");
                if (string.IsNullOrEmpty(username))
                {
                    username = HttpContext.Session.GetString("nname");
                    if (string.IsNullOrEmpty(username)) return Redirect("~/Home");
                }

                if (!string.IsNullOrEmpty(prm.Name))
                {
                    if (string.IsNullOrEmpty(prm.CreateBy)) prm.CreateBy = username;

                    var result = JsonConvert.DeserializeObject<ResponseEnt>(_surgeon.Update(prm));
                    if (!result.status)
                    {
                        HttpContext.Session.SetString("TmpError", result.message);
                        _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.UpdateSurgeon-" + result.message, CreateBy = "system", CreateDate = DateTime.Now });
                    }
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.UpdateSurgeon.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }
            return RedirectToAction(nameof(Surgeon));
        }

        public bool DeleteSurgeon(int id)
        {
            var result = false;

            try
            {
                var username = HttpContext.Session.GetString("uname");
                if (string.IsNullOrEmpty(username))
                {
                    username = HttpContext.Session.GetString("nname");
                    if (string.IsNullOrEmpty(username)) return false;
                }

                if (id > 0)
                {
                    var resp = JsonConvert.DeserializeObject<ResponseEnt>(_surgeon.Remove(id, username));
                    if (resp.status)
                    {
                        result = true;
                    }
                    else
                    {
                        HttpContext.Session.SetString("TmpError", resp.message);
                        _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.DeleteSurgeon-" + resp.message, CreateBy = "system", CreateDate = DateTime.Now });
                    }
                }
            }
            catch (Exception ex)
            {
                HttpContext.Session.SetString("TmpError", ex.Message);
                _log.Insert(new MLogger { LogType = EnLog.Error, Message = "Master.DeleteSurgeon.Ex-" + ex.Message, CreateBy = "system", CreateDate = DateTime.Now });
            }

project/NRG_Backend/Areas/SA/Views/Shared/_Header.cshtml
<header class="topbar">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <div class="navbar-header">
            <a class="navbar-brand" href="index.html">
                <b>
                    <img src="~/material-pro/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                    <img src="~/material-pro/assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />
                </b>
                <span>
                    <img src="~/material-pro/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                    <img src="~/material-pro/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />
                </span>
            </a>
        </div>
        <div class="navbar-collapse">
            <ul class="navbar-nav mr-auto mt-md-0">
                <li class="nav-item">
                    <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>

project/NRG_Backend/Areas/SA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="~/material-pro/assets/images/favicon.png">
    <title>NERVA Admin</title>
    <link href="~/material-pro/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/datatables/media/css/dataTables.bootstrap4.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/css-chart/css-chart.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/vectormap/jquery-jvectormap-2.0.2.css" rel="stylesheet">
    <link href="~/material-pro/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" />
    <link href="~/material-pro/assets/plugins/Magnific-Popup-master/dist/magnific-popup.css" rel="stylesheet" />
    <link href="~/material-pro/dark/css/style.css" rel="stylesheet" />
    <link href="~/material-pro/dark/css/colors/green-dark.css" id="theme" rel="stylesheet">
    <link href="~/material-pro/dark/css/icons/font-awesome/css/fontawesome-all.css" rel="stylesheet" />
    <link href="~/justdo/css/sweetalert.css" rel="stylesheet" />
    @*<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet" />*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body class="fix-header fix-sidebar card-no-border">
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <div id="main-wrapper">
        @await Html.PartialAsync("~/Areas/SA/Views/Shared/_Header.cshtml")
        @await Html.PartialAsync("~/Areas/SA/Views/Shared/_LeftSidebar.cshtml")
        <div class="page-wrapper">
            <div class="container-fluid">
                @RenderBody()
            </div>
            <footer class="footer"> ©@DateTime.Now.Year. Random Studio ID use Material Pro Admin Template by wrappixel.com</footer>
        </div>
    </div>

    @*<script src="~/material-pro/assets/plugins/jquery/jquery.min.js"></script>*@
    <script src="~/material-pro/assets/plugins/popper/popper.min.js"></script>
    <script src="~/material-pro/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/material-pro/dark/js/jquery.slimscroll.js"></script>
    <script src="~/material-pro/dark/js/waves.js"></script>
    <script src="~/material-pro/dark/js/sidebarmenu.js"></script>
    <script src="~/material-pro/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="~/material-pro/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script src="~/material-pro/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="~/material-pro/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script src="~/material-pro/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <script src="~/material-pro/dark/js/custom.min.js"></script>
    <script src="~/material-pro/assets/plugins/chartist-js/dist/chartist.min.js"></script>
    <script src="~/material-pro/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js"></script>
    <script src="~/material-pro/assets/plugins/vectormap/jquery-jvectormap-2.0.2.min.js"></script>
    <script src="~/material-pro/assets/plugins/vectormap/jquery-jvectormap-us-aea-en.js"></script>
    <script src="~/material-pro/dark/js/dashboard3.js"></script>
    <script src="~/material-pro/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
    <script src="~/material-pro/assets/plugins/datatables/datatables.min.js"></script>
    <script src="~/material-pro/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <!-- start - This is for export functionality only -->
    @*<script src="http://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
        <script src="http://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
        <script src="http://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
        <script src="http://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
        <script src="http://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
        <script src="http://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>*@
    <!-- end - This is for export functionality only -->
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.js"></script>*@
    <script src="~/material-pro/assets/plugins/Magnific-Popup-master/dist/jquery.magnific-popup.min.js"></script>
    <script src="~/material-pro/assets/plugins/Magnific-Popup-master/dist/jquery.magnific-popup-init.js"></script>
    <script src="~/justdo/js/sweetalert.min.js"></script>
</body>
</html>

project/NRG_Backend/Areas/SA/Views/Shared/_LeftSidebar.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<aside class="left-sidebar">
    <div class="scroll-sidebar">
        <div class="user-profile">
            <div class="profile-text">
                <a href="#" role="button">@HttpContextAccessor.HttpContext.Session.GetString("ufullname")</a>
            </div>
        </div>
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap">MENU</li>
                <li>
                    <a class="waves-effect waves-dark" href="@Url.Action("Index", "Default", new { area = "SA" })"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard </span></a>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-briefcase"></i><span class="hide-menu">Master Data</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("Hospital", "Master", new { area = "SA" })">Rumah Sakit</a></li>
                        <li><a href="@Url.Action("Patient", "Master", new { area = "SA" })">Pasien</a></li>
                        <li><a href="@Url.Action("Surgeon", "Master", new { area = "SA" })">Tindakan Bedah Saraf</a></li>
                    </ul>
                </li>
                <li>
                    <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="fa fa-user-md"></i><span class="hide-menu">Checkup Data</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="@Url.Action("Index", "Control", new { area = "SA" })">Pasien Control</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
    <div class="sidebar-footer">
        @*<a href="#" class="link" data-toggle="tooltip" title="Settings"><i class="ti-settings"></i></a>*@
        <a href="@Url.Action("Logout", "Home", new { id = HttpContextAccessor.HttpContext.Session.GetString("uid") })" class="link" data-toggle="tooltip" title="Logout"><i class="mdi mdi-power"></i></a>
    </div>
</aside>

project/NRG_Backend/Areas/SA/Views/Shared/_RightSidebar.cshtml
<div class="right-sidebar">
    <div class="slimscrollright">
        <div class="rpanel-title"> Service Panel <span><i class="ti-close right-side-toggle"></i></span> </div>
        <div class="r-panel-body">
            <ul id="themecolors" class="m-t-20">
                <li><b>With Light sidebar</b></li>
                <li><a href="javascript:void(0)" data-theme="default" class="default-theme">1</a></li>
                <li><a href="javascript:void(0)" data-theme="green" class="green-theme">2</a></li>
                <li><a href="javascript:void(0)" data-theme="red" class="red-theme">3</a></li>
                <li><a href="javascript:void(0)" data-theme="blue" class="blue-theme working">4</a></li>
                <li><a href="javascript:void(0)" data-theme="purple" class="purple-theme">5</a></li>
                <li><a href="javascript:void(0)" data-theme="megna" class="megna-theme">6</a></li>
                <li class="d-block m-t-30"><b>With Dark sidebar</b></li>
                <li><a href="javascript:void(0)" data-theme="default-dark" class="default-dark-theme">7</a></li>
                <li><a href="javascript:void(0)" data-theme="green-dark" class="green-dark-theme">8</a></li>
                <li><a href="javascript:void(0)" data-theme="red-dark" class="red-dark-theme">9</a></li>
                <li><a href="javascript:void(0)" data-theme="blue-dark" class="blue-dark-theme">10</a></li>
                <li><a href="javascript:void(0)" data-theme="purple-dark" class="purple-dark-theme">11</a></li>
                <li><a href="javascript:void(0)" data-theme="megna-dark" class="megna-dark-theme ">12</a></li>
            </ul>
            <ul class="m-t-20 chatonline">
                <li><b>Chat option</b></li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/1.jpg" alt="user-img" class="img-circle"> <span>Varun Dhavan <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/2.jpg" alt="user-img" class="img-circle"> <span>Genelia Deshmukh <small class="text-warning">Away</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/3.jpg" alt="user-img" class="img-circle"> <span>Ritesh Deshmukh <small class="text-danger">Busy</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/4.jpg" alt="user-img" class="img-circle"> <span>Arijit Sinh <small class="text-muted">Offline</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/5.jpg" alt="user-img" class="img-circle"> <span>Govinda Star <small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/6.jpg" alt="user-img" class="img-circle"> <span>John Abraham<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/7.jpg" alt="user-img" class="img-circle"> <span>Hritik Roshan<small class="text-success">online</small></span></a>
                </li>
                <li>
                    <a href="javascript:void(0)"><img src="~/material-pro/assets/images/users/8.jpg" alt="user-img" class="img-circle"> <span>Pwandeep rajan <small class="text-success">online</small></span></a>
                </li>
            </ul>
        </div>
    </div>
</div>